language: php
before_install:
  - npm install -g dredd
  - bundle install
  - composer install

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7"

script:
  - bundle exec cucumber
  - vendor/bin/phpunit    
