language: php
before_install:
  - npm install -g dredd
  - bundle install
  - composer install

php:
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"    
  - "5.6"

script:
  - bundle exec cucumber
  - vendor/bin/phpunit    
